### PR TITLE
Make reducers with dependencies always return object of shape `{value, _dependencies}`

### PR DESCRIPTION
**Pull request by aikoven**
Original issue: https://github.com/slorber/rereduce/issues/4

### CODE REVIEW

**Comment by slorber** [comment]
thanks :)

**Comment by aikoven** [comment]
Can you please release new version to NPM?

**Comment by slorber** [comment]
ooh yes sorry @aikoven just released rereduce@0.1.0

**Comment by aikoven** [comment]
Thanks!

**Pull request merged**
